#!/bin/sh

set -ex

target=scan@tinfoil

DEVICE='brother4:bus6;dev1'
DPI=300

dest="$1"
shift

if test -z "$dest"; then
  echo "Usage: scan-remote destination [scan.rb options]"  1>&2
  exit 1
fi

if ! echo "$dest" |egrep -q '\.pdf$'; then
  echo "Adjsting $dest -> $dest.pdf" 1>&2
  dest="$dest".pdf
fi

tempdir=`ssh $target 'mktemp -d /tmp/scan-remote-XXXXXX'`
ssh $target "~/apps/scan-to-pdf/scan.rb -d '$DEVICE' -r $DPI --letter -o '$tempdir/out.pdf' $*"

scp $target:$tempdir/out.pdf $dest
scp $target:$tempdir/out-raw.pdf `echo $dest |sed -e s/.pdf/-raw.pdf/`

ssh $target "rm -rf $tempdir"
